# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gestor_de_estoque_pb2 as gestor__de__estoque__pb2


class GestorDeEstoqueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cadastrar = channel.unary_unary(
                '/gestor_de_estoque.GestorDeEstoque/Cadastrar',
                request_serializer=gestor__de__estoque__pb2.DadosCadastro.SerializeToString,
                response_deserializer=gestor__de__estoque__pb2.SseUrl.FromString,
                )
        self.ObterRelatorioEstoque = channel.unary_unary(
                '/gestor_de_estoque.GestorDeEstoque/ObterRelatorioEstoque',
                request_serializer=gestor__de__estoque__pb2.MensagemVazia.SerializeToString,
                response_deserializer=gestor__de__estoque__pb2.RelatorioEstoque.FromString,
                )
        self.ObterRelatorioFluxoMovimentacoes = channel.unary_unary(
                '/gestor_de_estoque.GestorDeEstoque/ObterRelatorioFluxoMovimentacoes',
                request_serializer=gestor__de__estoque__pb2.Periodo.SerializeToString,
                response_deserializer=gestor__de__estoque__pb2.RelatorioFluxoMovimentacoes.FromString,
                )
        self.ObterRelatorioSemSaida = channel.unary_unary(
                '/gestor_de_estoque.GestorDeEstoque/ObterRelatorioSemSaida',
                request_serializer=gestor__de__estoque__pb2.Periodo.SerializeToString,
                response_deserializer=gestor__de__estoque__pb2.RelatorioSemSaida.FromString,
                )
        self.LancarEntrada = channel.unary_unary(
                '/gestor_de_estoque.GestorDeEstoque/LancarEntrada',
                request_serializer=gestor__de__estoque__pb2.DadosEntrada.SerializeToString,
                response_deserializer=gestor__de__estoque__pb2.EstadoResposta.FromString,
                )
        self.LancarSaida = channel.unary_unary(
                '/gestor_de_estoque.GestorDeEstoque/LancarSaida',
                request_serializer=gestor__de__estoque__pb2.DadosSaida.SerializeToString,
                response_deserializer=gestor__de__estoque__pb2.EstadoResposta.FromString,
                )


class GestorDeEstoqueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Cadastrar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterRelatorioEstoque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterRelatorioFluxoMovimentacoes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterRelatorioSemSaida(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LancarEntrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LancarSaida(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestorDeEstoqueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cadastrar': grpc.unary_unary_rpc_method_handler(
                    servicer.Cadastrar,
                    request_deserializer=gestor__de__estoque__pb2.DadosCadastro.FromString,
                    response_serializer=gestor__de__estoque__pb2.SseUrl.SerializeToString,
            ),
            'ObterRelatorioEstoque': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterRelatorioEstoque,
                    request_deserializer=gestor__de__estoque__pb2.MensagemVazia.FromString,
                    response_serializer=gestor__de__estoque__pb2.RelatorioEstoque.SerializeToString,
            ),
            'ObterRelatorioFluxoMovimentacoes': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterRelatorioFluxoMovimentacoes,
                    request_deserializer=gestor__de__estoque__pb2.Periodo.FromString,
                    response_serializer=gestor__de__estoque__pb2.RelatorioFluxoMovimentacoes.SerializeToString,
            ),
            'ObterRelatorioSemSaida': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterRelatorioSemSaida,
                    request_deserializer=gestor__de__estoque__pb2.Periodo.FromString,
                    response_serializer=gestor__de__estoque__pb2.RelatorioSemSaida.SerializeToString,
            ),
            'LancarEntrada': grpc.unary_unary_rpc_method_handler(
                    servicer.LancarEntrada,
                    request_deserializer=gestor__de__estoque__pb2.DadosEntrada.FromString,
                    response_serializer=gestor__de__estoque__pb2.EstadoResposta.SerializeToString,
            ),
            'LancarSaida': grpc.unary_unary_rpc_method_handler(
                    servicer.LancarSaida,
                    request_deserializer=gestor__de__estoque__pb2.DadosSaida.FromString,
                    response_serializer=gestor__de__estoque__pb2.EstadoResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gestor_de_estoque.GestorDeEstoque', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GestorDeEstoque(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Cadastrar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestor_de_estoque.GestorDeEstoque/Cadastrar',
            gestor__de__estoque__pb2.DadosCadastro.SerializeToString,
            gestor__de__estoque__pb2.SseUrl.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObterRelatorioEstoque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestor_de_estoque.GestorDeEstoque/ObterRelatorioEstoque',
            gestor__de__estoque__pb2.MensagemVazia.SerializeToString,
            gestor__de__estoque__pb2.RelatorioEstoque.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObterRelatorioFluxoMovimentacoes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestor_de_estoque.GestorDeEstoque/ObterRelatorioFluxoMovimentacoes',
            gestor__de__estoque__pb2.Periodo.SerializeToString,
            gestor__de__estoque__pb2.RelatorioFluxoMovimentacoes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObterRelatorioSemSaida(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestor_de_estoque.GestorDeEstoque/ObterRelatorioSemSaida',
            gestor__de__estoque__pb2.Periodo.SerializeToString,
            gestor__de__estoque__pb2.RelatorioSemSaida.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LancarEntrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestor_de_estoque.GestorDeEstoque/LancarEntrada',
            gestor__de__estoque__pb2.DadosEntrada.SerializeToString,
            gestor__de__estoque__pb2.EstadoResposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LancarSaida(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestor_de_estoque.GestorDeEstoque/LancarSaida',
            gestor__de__estoque__pb2.DadosSaida.SerializeToString,
            gestor__de__estoque__pb2.EstadoResposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
